### PR TITLE
Server stream

### PR DESCRIPTION
**Pull request by alsofr**
@phiSgr I'm not planning to merge this one as is, I just wanted to have your early opinion. Is this how you imagined it?

This code runs properly and the total processing time is measured properly.
Sending all the messages back to the session is still missing, currently just sending the last one.

### CODE REVIEW

**Comment by phiSgr** [comment]
My design is very far from it. I want to unify server streaming and bidi-streaming using actors.

I'll leave this PR open to motivate me working on it.

**Comment by maheshmothukuri** [comment]
Hi @alsofr .

i pulled your branch that had support for server streaming, In first go it looks good but as you mentioned currently it is not combining the result of all the responses into one gRPC response. By any chance is it ready by now ?

Thanks

**Comment by phiSgr** [comment]
Closed with b164e57

**Comment by alsofr** [comment]
Thank you @phiSgr , much appreciated!

**Comment by UserNoOne** [comment]
Awesome @phiSgr , Thanks a lot

**Pull request closed without merging**
